name: decorator_generator
version: 0.0.1
description: Python's decorators in dart
author: Dinesh Ahuja <dev@kabiir.me>
homepage: https://github.com/devkabiir/decorator/

dependencies:
  decorator: ^0.0.1
  build_config: ^0.3.0
  build: ^1.0.0
  source_gen: ^0.9.0
  logging: <1.0.0
  code_builder: ^3.0.0
  recase: ^2.0.0
  path: ^1.0.0
  dart_style: ^1.0.0
  analyzer: any

dev_dependencies:
  test: ^1.0.0
  build_test: ^0.10.0
  build_runner: ^1.0.0
  pre_commit:
    git: https://github.com/devkabiir/pre_commit/

dependency_overrides:
  decorator:
    path: ../decorator

environment:
  sdk: '>=2.0.0 <3.0.0'
